### ISSUE TITLE
REGISTRY_PASSWORDの再設定

### ISSUE THREAD

**Issue by xuwei-k** [scalajp/scala_text_pdf#1]
移管したので消えた。

https://github.com/scalajp/scala_text_pdf/blob/42591e4be3641d7f6bf1f540225a0042f89a9ac7/travis/deploy_image.sh#L6

この設定無くても、最低限動くっぽい？(よくわかってない)が、必要なら再設定。
必要ないなら関連するコード消す

**Comment by y-yu** [comment]
これは必要ですね……。CIでもし`Dockerfile`に変更があったらここにビルド用のイメージをpushするので。（現在はおそらく`Dockerfile`をいじっていないためエラーになっていないが）

**Comment by xuwei-k** [comment]
自分がDM的なにかで教えてもらって設定するのと、y-yuさんをコミッターにしてしまって設定してもらうの、どっちがいいかなぁ。
今後のメンテも考えると後者かな。
コミッターにする場合の条件的なの何か決まってるのか謎だが。
とりあえず @kmizu さんにメンションするか

**Comment by y-yu** [comment]
ちょっとこの状況だと僕が（一時的にも）コミッターになるしかないですね……。このパスワードはTravis CIで設定しないといけないので。あと、これまではここに僕のDocker Hubアカウントのパスワードをいれてましたが、どうやらアクセストークンがDocker Hubに実装されたのでついでにこちらにします。

- https://blog.docker.com/2019/09/docker-hub-new-personal-access-tokens/

**Comment by xuwei-k** [comment]
まぁ許可より謝罪で(ぇ)、コミッターにしちゃうか

**Comment by taisukeoe** [comment]
なるほどです。コミッタになっていただく感じで良いと思います。
ありがとうございます🙏

（ @kmizu さん不在のまま話を進めていくスタイル･･････）

**Comment by xuwei-k** [comment]
adminでinvite送った

![F35C00F2-7560-4BFF-92CD-803C09E53DC7](https://user-images.githubusercontent.com/389787/65814477-35706c80-e21d-11e9-8d04-2f74c90fc830.jpeg)

**Comment by xuwei-k** [comment]
ちなみに、scala_text本体のpull reqだかissueに書いたけど、この設定以外はすでに大体完了してるので、pdf自体も(Dcokerfile更新したりしない場合は)既に自動更新されるようになってます

**Comment by y-yu** [comment]
#3 がうまくいったので解決とします。
